### ISSUE TITLE
taximeter problem.

### ISSUE THREAD

**Issue by ghost** [qbcore-framework/qb-taxijob#32]
taximeter working like birds look not mph or kmh amount. if you activate it x point then drive away price starts increasing but if you turn back to starting point or nearby price starts decreasing.  expl. :/
![image](https://user-images.githubusercontent.com/100320811/158048521-6f93bb37-4f3b-4207-9fd2-a26fef2281ad.png)

**Comment by SW1FT** [comment]
`calculateFareAmount()` needs to be refactored. I'll try to patch it and submit a PR.

EDIT: Fixed in https://github.com/SW1FT/qb-taxijob/pull/1, also has a few other fixes too.

**Comment by GhzGarage** [comment]
> `calculateFareAmount()` needs to be refactored. I'll try to patch it and submit a PR.
> 
> EDIT: Fixed in [SW1FT#1](https://github.com/SW1FT/qb-taxijob/pull/1), also has a few other fixes too.

Are you going to PR this or no?

**Comment by SW1FT** [comment]
> > `calculateFareAmount()` needs to be refactored. I'll try to patch it and submit a PR.
> > EDIT: Fixed in [SW1FT#1](https://github.com/SW1FT/qb-taxijob/pull/1), also has a few other fixes too.
> 
> Are you going to PR this or no?

#39 is ready.
