### ISSUE TITLE
[BUG] NPC unlimited journey

### ISSUE THREAD

**Issue by ChickenDipper1** [qbcore-framework/qb-taxijob#52]
**Describe the bug**
You can earn as much as you want from a single NPC fare by driving the wrong way for as long as you want before dropping the NPC at the destination, removing the need to drive unpaid to pickup a new NPC at any time.

**To Reproduce**
1. Take taxi job, get taxi and enable npc missions
2. Pickup first npc and drive around as much as you want.
3. Pay keeps going up for miles travelled.
4. Drop off npc when ready.

**Expected behavior**
Pay should be based on distance to npc destination and cap at this even if you drive further than needed.

Or

The npc should refuse to pay/get out of the taxi when it stops and not pay.

**Screenshots**
N/A

**Questions (please complete the following information):**
 - When you last updated: 2 weeks ago
 - Are you using custom resource? which ones? N/A
 - Have you renamed `qb-` to something custom? No

**Additional context**
N/A

**Comment by Leslija** [comment]
Sounds fair. In real life you can also drive around and get paid for that.. No matter if you took two or three NPC, the price would be the same as with one driving around, as it is defined in the files..

**Comment by tobsval** [comment]
This kinda forces you to take the path that the GPS suggests, which might not always be viable (e.g.: road blocks, accidents, RP situations, ...)

**Comment by KeeganAI** [comment]
fixed in the next push
