### ISSUE TITLE
[BUG] Missing checking / Taximeter Toggling

### ISSUE THREAD

**Issue by Leslija** [qbcore-framework/qb-taxijob#56]
I suck at pull requests, I apologize for that. I know someone will do it better than me! 

So you can turn on the taximeter counting before the NPC mission.... Then you start the NPC mission and when you pick up/call the NPC, the taximeter stops counting (it toggles the taximeter without checking if it was already active)... If it was active, it puts it to inactive and vice versa. If you never started the taximeter counting before NPC mission, it works fine. 

In the image, I turned on the taximeter before the NPC mission, drove around and when I picked up the NPC, the taximeter stopped. It did not clear the values. 
![image](https://user-images.githubusercontent.com/19732312/190485319-4c6683bc-30be-4fe4-8ff9-e89790a647fc.png)

But then I noticed - Ohh, it doesn't count? 
What I do: I manually toggle the taximeter from the radial menu, BUT the count starts again at 0 and from the point where I toggled it back to started, not at the point where I picked up the NPC. .

My suggestion/The fix: Check in the function callNpcPoly() if the meterActive is true then resetMeter() otherwise toggle the meter to started.

I hope it was understandable.

**Comment by PT-Mohamed-Hussein** [comment]
Wait next update and it will be fixed soon dw
