### ISSUE TITLE
[BUG] Infinite money by abusing the taxi toll.

### ISSUE THREAD

**Issue by spicebag** [qbcore-framework/qb-taxijob#59]
**Describe the bug**
When using the taxi job, you can make infinite money by taking a passenger and driving around a lot before delivering the passenger.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start Job
2. Take Passenger and start the journey
3. Infinite money as long as you keep driving
4. Deliver passengers and get a bunch of money.

**Expected behaviour**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Reinstalled clean this week.
 
- Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
Yes, none of them effect qb-taxijob though.

 - Have you renamed `qb-` to something custom? [e.g. yes/no]
 No.

**Additional context**
N/A

**Comment by spicebag** [comment]
Expected behaviour
A clear and concise description of what you expected to happen.

I expect the player to not get infinite money, either have a timer for delivery times etc.

**Comment by S33G** [comment]
Thanks for reporting, we'll take a look

**Comment by NikoClapz** [comment]
> Thanks for reporting, we'll take a look

Any updates on this?

**Comment by 1llusiv3r** [comment]
an easy fix would be to set a timer to countdown when you pickup the local, if after a certain time you don't drop off the passenger  create a notification saying the passenger is calling the police and wants to be let out then send a dispatch notification for kidnapping or something with a description of the vehicle.

**Comment by aymannajim** [comment]
> an easy fix would be to set a timer to countdown when you pickup the local, if after a certain time you don't drop off the passenger create a notification saying the passenger is calling the police and wants to be let out then send a dispatch notification for kidnapping or something with a description of the vehicle.

that's way too complicated, an easier fix could be changing this single line in server/main.lua
from:
```
if randomAmount == r1 or randomAmount == r2 then Payment = Payment + math.random(10, 20) end
```
to this:
```
Payment = math.random(100, 500)
```
which will make the player get paid between $100 and $500, you can customize it as you wish.

**Comment by KeeganAI** [comment]
No, as i checked, it's based on the distance, if you move away from the delivery location, the total price will decrease.
