### ISSUE TITLE
[BUG] Management

### ISSUE THREAD

**Issue by xxUnknown13xx** [qbcore-framework/qb-taxijob#60]
How does the "Taxi Business" earn money? If doing some fares, as a regular driver and then switching to Owner and checking the Money management menu, Business earns $0. So what's the point this script even having a Management Menu If the business earns Nothing?!

**Comment by PT-Mohamed-Hussein** [comment]
We are considering adding some new features for management in the near future. However, currently, all the fares go directly to the driver. If the community approves, we may introduce a percentage of the fare to be allocated to the management.
