### ISSUE TITLE
Payment into boss menu

### ISSUE THREAD

**Issue by DoctorFrosty** [qbcore-framework/qb-taxijob#73]
With the new system to pay into the boss menu, when the setting is turned on its throwing out a My SQL error

[Code]
if Config.Management then
                MySQL.insert('INSERT INTO management_funds (job_name, amount, type) VALUES (:job_name, :amount, :type) ON DUPLICATE KEY UPDATE amount = :amount',
                {
                    ['job_name'] = Config.jobRequired,
                    ['amount'] = Payment,
                    ['type'] = 'boss'
                })
                
[Error]

SCRIPT ERROR: @qb-taxijob/server/main.lua:23: attempt to index a nil value (global 'MySQL')                

**To Reproduce**
set Management = true, in Config.lua
take a customer to their destination and attempt to collect payment

**Expected behaviour**
money to go into management fund

**Comment by GhzGarage** [comment]
Sorry about that oversight! I've fixed it here https://github.com/qbcore-framework/qb-taxijob/commit/f030d4c8eddd0e80a85adab0c8f17911ec928d06
