### ISSUE TITLE
duty blip text

### ISSUE THREAD

**Issue by DoctorFrosty** [qbcore-framework/qb-taxijob#74]
**Describe the bug**
code for the duty blip text doesn't change when going on and off duty. also looks like the text output is printing the word "info." into the text box 

f8 is also printing "Missing phrase for key: "on_duty""

**To Reproduce**
go to on/off duty blip, blip works but text doesn't change when on or off duty,
duty status still changes correctly, and notification of duty change also works correctly

**Expected behavior**
to shop duty status .

[CODE]

    dutyZone:onPlayerInOut(function(isPointInside)
        if isPointInside then
            dutyKey = true
            if not PlayerJob.onduty then
                exports['qb-core']:DrawText(Lang:t('info.on_duty'),'left')
            else
                exports['qb-core']:DrawText(Lang:t('info.off_duty'),'left')
            end
            onDuty()
        else
            dutyKey = false
            exports['qb-core']:HideText()
        end
    end)
end)

**Comment by KeeganAI** [comment]
im on it!

**Comment by DoctorFrosty** [comment]
> im on it!

Legend. thanks for the fast replies, love the taxi script :)

**Comment by KeeganAI** [comment]
> > im on it!
> 
> Legend. thanks for the fast replies, love the taxi script :)

spent many hours in these days, appreciate it

**Comment by DoctorFrosty** [comment]
> > > im on it!
> > 
> > 
> > Legend. thanks for the fast replies, love the taxi script :)
> 
> spent many hours in these days, appreciate it

Hey bud, not sure if anyone has tested this but still having issues getting the text to swap depending weather on duty or not. its all displaying as it looks like it should from the code. but the text box always says go off duty no matter what the duty state is? any ideas?
