### ISSUE TITLE
[BUG] Duplicate `info.on_duty` in translations, no  `info.off_duty`, improper default return.

### ISSUE THREAD

**Issue by xhorntail** [qbcore-framework/qb-taxijob#80]
**Describe the bug**
All translation files have a duplicate index at: `info.on_duty`. This breaks the ability to take a job, as the `info.off_duty` is called and not found. 
Translations probably shouldn't default to returning nil on improper schema..

**To Reproduce**
1. Look at any of the translation files.

**Comment by t0r3tto** [comment]
fixed in https://github.com/qbcore-framework/qb-taxijob/commit/03434e85eed20e9d1a09cebfc9443e51d2700f94
