### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DispersiaRoleplay** [qbcore-framework/qb-taxijob#83]
![image_2024-05-12_071849890](https://github.com/qbcore-framework/qb-taxijob/assets/155019886/85d1a6d1-0a25-48c2-8dde-7853f5a9f962)

**Comment by ChristianBDev** [comment]
@Psycho66626  can you shoe me your config.lua line 15 or screenshot of a bit of the code so we can assist further

**Comment by DispersiaRoleplay** [comment]
literally the same, sir. I just replaced old version to this one.

When I deleted leter t in this line, my server stopped loading xD

![image_2024-05-13_153118940](https://github.com/qbcore-framework/qb-taxijob/assets/155019886/7e38b383-b040-4a38-90af-136c3dfce676)
